name: CD

on:
  workflow_dispatch:
  # Only run if triggered manually
  # push:
  #   branches: [ master ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
  tag-release:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version package.json -r'
      - uses: actions/create-release@v1  
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.value }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false